name: youtube_player_flutter
description: A customizable YouTube player for Flutter applications.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: ^4.0.4 # giữ nếu bạn dùng iframe bên trong

dev_dependencies:
  flutter_lints: ^3.0.1
